#!/bin/sh
echo "one moment just check if it compiles"
# npm run build && npm run start
npm version --commit-hooks false --git-tag-version false patch
# Actualizar el README.md
npm run uvr
# Agregar los cambios en los archivos de versión en la raíz
git add package.json
git add package-lock.json
git add README.md
